version: '3'
services:
    swarm-api:
        image: 'swarm-backend'
        ports:
            - '4000:4000'
        networks:
            - backend
        environment:
            - DEMO_ALLOWEDORIGINS=http://localhost:8300
            - SERVER_PORT=4000
        deploy:
            replicas: 1
            update_config: {parallelism: 1}
            restart_policy: {condition: on-failure}
            placement:
                constraints: ['node.labels.service2 == springboot']
    swarm-web:
        image: 'swarm-frontend'
        ports:
            - '8300:80'
        networks:
            - backend
        environment:
            - VUE_APP_BACKEND_HOST=http://localhost:4000
        depends_on:
            - swarm-api
        deploy:
            replicas: 1
            update_config: {parallelism: 1}
            restart_policy: {condition: on-failure}
            placement:
                constraints: ['node.labels.service == nodejs']
    visualizer:
        image: 'dockersamples/visualizer:stable'
        ports:
            - '8083:8080'
        stop_grace_period: 1m30s
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
networks:
    backend:                
